from __future__ import annotations

from config.settings import logger, settings

GEMINI_API_KEY = settings.GEMINI_API_KEY
GOOGLE_GENAI_USE_VERTEXAI = settings.GOOGLE_GENAI_USE_VERTEXAI

TAVILY_API_KEY = settings.TAVILY_API_KEY

LLM_ORCHESTRATOR_MODEL = settings.LLM_ORCHESTRATOR_MODEL
LLM_ORCHESTRATOR_FALLBACK = settings.LLM_ORCHESTRATOR_FALLBACK
LLM_SUBAGENT_MODEL = settings.LLM_SUBAGENT_MODEL
LLM_SUBAGENT_FALLBACK = settings.LLM_SUBAGENT_FALLBACK
LLM_TEMPERATURE_ORCHESTRATOR = settings.LLM_TEMPERATURE_ORCHESTRATOR
LLM_TEMPERATURE_SUBAGENT = settings.LLM_TEMPERATURE_SUBAGENT

LANGSMITH_API_KEY = settings.LANGSMITH_API_KEY
LANGSMITH_PROJECT = settings.LANGSMITH_PROJECT
LANGCHAIN_TRACING_V2 = settings.LANGCHAIN_TRACING_V2

AUTH_MODE = settings.AUTH_MODE
API_AUTH_KEY = settings.API_AUTH_KEY

CORS_ORIGINS = settings.CORS_ORIGINS

REDIS_URL = settings.REDIS_URL

REQUEST_TIMEOUT_SECONDS = settings.REQUEST_TIMEOUT_SECONDS

CHECKPOINTER_BACKEND = settings.CHECKPOINTER_BACKEND
STORE_BACKEND = settings.STORE_BACKEND

GOOGLE_CLIENT_ID = settings.GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET = settings.GOOGLE_CLIENT_SECRET
OAUTH_REDIRECT_URI = settings.OAUTH_REDIRECT_URI
SESSION_SECRET_KEY = settings.SESSION_SECRET_KEY
AUTH_DEV_BYPASS = settings.AUTH_DEV_BYPASS

SHARE_TTL_DAYS = settings.SHARE_TTL_DAYS

# Cost tracking
SESSION_BUDGET_LIMIT_USD = settings.SESSION_BUDGET_LIMIT_USD
BUDGET_WARNING_THRESHOLD = settings.BUDGET_WARNING_THRESHOLD
ADMIN_EMAILS = settings.ADMIN_EMAILS

# Model routing tiers
MODEL_TIER_CHEAP = settings.MODEL_TIER_CHEAP
MODEL_TIER_STANDARD = settings.MODEL_TIER_STANDARD
MODEL_TIER_PREMIUM = settings.MODEL_TIER_PREMIUM
SUBAGENT_MODEL_OVERRIDES = settings.SUBAGENT_MODEL_OVERRIDES

__all__ = [
    "API_AUTH_KEY",
    "ADMIN_EMAILS",
    "AUTH_DEV_BYPASS",
    "AUTH_MODE",
    "BUDGET_WARNING_THRESHOLD",
    "CHECKPOINTER_BACKEND",
    "CORS_ORIGINS",
    "GEMINI_API_KEY",
    "GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
    "GOOGLE_GENAI_USE_VERTEXAI",
    "LANGSMITH_API_KEY",
    "LANGSMITH_PROJECT",
    "LLM_ORCHESTRATOR_FALLBACK",
    "LLM_ORCHESTRATOR_MODEL",
    "LLM_SUBAGENT_FALLBACK",
    "LLM_SUBAGENT_MODEL",
    "LLM_TEMPERATURE_ORCHESTRATOR",
    "LLM_TEMPERATURE_SUBAGENT",
    "MODEL_TIER_CHEAP",
    "MODEL_TIER_PREMIUM",
    "MODEL_TIER_STANDARD",
    "OAUTH_REDIRECT_URI",
    "REDIS_URL",
    "REQUEST_TIMEOUT_SECONDS",
    "SESSION_BUDGET_LIMIT_USD",
    "SESSION_SECRET_KEY",
    "SHARE_TTL_DAYS",
    "STORE_BACKEND",
    "SUBAGENT_MODEL_OVERRIDES",
    "TAVILY_API_KEY",
    "logger",
    "settings",
]
