from __future__ import annotations

from config.settings import logger, settings

GEMINI_API_KEY = settings.GEMINI_API_KEY
GOOGLE_GENAI_USE_VERTEXAI = settings.GOOGLE_GENAI_USE_VERTEXAI

TAVILY_API_KEY = settings.TAVILY_API_KEY

LLM_ORCHESTRATOR_MODEL = settings.LLM_ORCHESTRATOR_MODEL
LLM_ORCHESTRATOR_FALLBACK = settings.LLM_ORCHESTRATOR_FALLBACK
LLM_SUBAGENT_MODEL = settings.LLM_SUBAGENT_MODEL
LLM_SUBAGENT_FALLBACK = settings.LLM_SUBAGENT_FALLBACK
LLM_TEMPERATURE_ORCHESTRATOR = settings.LLM_TEMPERATURE_ORCHESTRATOR
LLM_TEMPERATURE_SUBAGENT = settings.LLM_TEMPERATURE_SUBAGENT

LANGSMITH_API_KEY = settings.LANGSMITH_API_KEY
LANGSMITH_PROJECT = settings.LANGSMITH_PROJECT
LANGCHAIN_TRACING_V2 = settings.LANGCHAIN_TRACING_V2

AUTH_MODE = settings.AUTH_MODE
API_AUTH_KEY = settings.API_AUTH_KEY

CORS_ORIGINS = settings.CORS_ORIGINS

REDIS_URL = settings.REDIS_URL

REQUEST_TIMEOUT_SECONDS = settings.REQUEST_TIMEOUT_SECONDS

CHECKPOINTER_BACKEND = settings.CHECKPOINTER_BACKEND
STORE_BACKEND = settings.STORE_BACKEND

__all__ = [
    "API_AUTH_KEY",
    "AUTH_MODE",
    "CHECKPOINTER_BACKEND",
    "CORS_ORIGINS",
    "GEMINI_API_KEY",
    "GOOGLE_GENAI_USE_VERTEXAI",
    "LANGSMITH_API_KEY",
    "LANGSMITH_PROJECT",
    "LLM_ORCHESTRATOR_FALLBACK",
    "LLM_ORCHESTRATOR_MODEL",
    "LLM_SUBAGENT_FALLBACK",
    "LLM_SUBAGENT_MODEL",
    "LLM_TEMPERATURE_ORCHESTRATOR",
    "LLM_TEMPERATURE_SUBAGENT",
    "REDIS_URL",
    "REQUEST_TIMEOUT_SECONDS",
    "STORE_BACKEND",
    "TAVILY_API_KEY",
    "logger",
    "settings",
]
