"""Shared Postgres durable tier for all stores (Supabase-friendly).

Role in the storage ladder: Redis (hot) -> Postgres (durable) -> SQLite
(disaster tier) -> memory (last resort). When ``DATABASE_URL`` is unset or
Postgres is unreachable this module returns ``None`` and every caller simply
behaves as it did before — SQLite, then memory.

Supabase notes:
- Use the session-mode/direct connection string (NOT the transaction-mode
  pooler on :6543) — transaction pooling breaks prepared statements and
  server-side cursors used by psycopg and LangGraph.
- ``prepare_threshold=0`` is set defensively for any pooled proxy.
- SSL is required: ``sslmode=require`` is appended when missing.

Usage:
    from pg_store import pg_fetchone, pg_execute

    row = await pg_fetchone("SELECT x FROM t WHERE k = $1", (key,))
    await pg_execute("INSERT INTO t (k, v) VALUES ($1, $2) ON CONFLICT (k) DO UPDATE SET v = $2", (k, v))
"""

from __future__ import annotations

import asyncio
import logging
import re
import time

from config import settings

logger = logging.getLogger("travel_agent.pg_store")

_SCHEMA_VERSION = 1

# Ported from sqlite_fallback._SCHEMA_SQL — same tables, Postgres dialect.
_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    applied_at DOUBLE PRECISION NOT NULL
);

-- ThreadStore
CREATE TABLE IF NOT EXISTS threads (
    thread_id TEXT PRIMARY KEY,
    user_tag TEXT NOT NULL,
    summary TEXT,
    created_at DOUBLE PRECISION,
    updated_at DOUBLE PRECISION,
    status TEXT DEFAULT 'idle',
    message_count INTEGER DEFAULT 0,
    search_text TEXT,
    pinned INTEGER DEFAULT 0,
    pinned_at DOUBLE PRECISION DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_threads_user_tag ON threads(user_tag);
CREATE INDEX IF NOT EXISTS idx_threads_updated ON threads(user_tag, updated_at DESC);

-- ShareStore
CREATE TABLE IF NOT EXISTS shares (
    token TEXT PRIMARY KEY,
    user_tag TEXT NOT NULL,
    thread_id TEXT,
    destination TEXT,
    itinerary_json TEXT,
    created_at DOUBLE PRECISION,
    expires_at DOUBLE PRECISION,
    image_base64 TEXT
);
CREATE INDEX IF NOT EXISTS idx_shares_user_tag ON shares(user_tag);

-- OAuth sessions
CREATE TABLE IF NOT EXISTS sessions (
    session_id TEXT PRIMARY KEY,
    payload_json TEXT,
    created_at DOUBLE PRECISION,
    expires_at DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);

-- CostStore
CREATE TABLE IF NOT EXISTS costs_session (
    thread_id TEXT PRIMARY KEY,
    user_id TEXT,
    total_input_tokens BIGINT,
    total_output_tokens BIGINT,
    total_cost_usd DOUBLE PRECISION,
    efficiency_ratio DOUBLE PRECISION,
    budget_limit_usd DOUBLE PRECISION,
    budget_reached INTEGER,
    created_at DOUBLE PRECISION
);
CREATE TABLE IF NOT EXISTS costs_subagent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id TEXT,
    subagent_name TEXT,
    input_tokens BIGINT,
    output_tokens BIGINT,
    cost_usd DOUBLE PRECISION,
    model_used TEXT,
    timestamp DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_costs_subagent_thread ON costs_subagent(thread_id);

-- FeedbackStore
CREATE TABLE IF NOT EXISTS feedback (
    key TEXT PRIMARY KEY,
    user_id TEXT,
    message_id TEXT,
    thread_id TEXT,
    rating TEXT,
    comment TEXT,
    created_at DOUBLE PRECISION,
    updated_at DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_feedback_thread ON feedback(thread_id);

-- SecurityStore
CREATE TABLE IF NOT EXISTS security_flags (
    flag_id TEXT PRIMARY KEY,
    user_hash TEXT,
    category TEXT,
    confidence DOUBLE PRECISION,
    source TEXT,
    thread_id TEXT,
    reasoning_snippet TEXT,
    created_at DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_security_flags_user ON security_flags(user_hash);
CREATE TABLE IF NOT EXISTS security_strikes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_hash TEXT,
    created_at DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_security_strikes_user ON security_strikes(user_hash);
CREATE TABLE IF NOT EXISTS security_cooldowns (
    user_hash TEXT PRIMARY KEY,
    cooldown_until DOUBLE PRECISION
);

-- ResearchCache
CREATE TABLE IF NOT EXISTS research_cache (
    key TEXT PRIMARY KEY,
    value TEXT,
    created_at DOUBLE PRECISION,
    expires_at DOUBLE PRECISION
);

-- GeocodeCache
CREATE TABLE IF NOT EXISTS geocode_cache (
    query_hash TEXT PRIMARY KEY,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    created_at DOUBLE PRECISION
);

-- FileStore
CREATE TABLE IF NOT EXISTS files (
    file_id TEXT PRIMARY KEY,
    user_tag TEXT,
    filename TEXT,
    content_type TEXT,
    size BIGINT,
    data_base64 TEXT,
    created_at DOUBLE PRECISION,
    expires_at DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_files_user_tag ON files(user_tag);

-- RateLimiter
CREATE TABLE IF NOT EXISTS rate_limits (
    key TEXT NOT NULL,
    timestamp DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (key, timestamp)
);

-- ObservabilityStore
CREATE TABLE IF NOT EXISTS observability_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    run_id TEXT,
    name TEXT,
    parent_run_id TEXT,
    input TEXT,
    output TEXT,
    error TEXT,
    tokens_in BIGINT DEFAULT 0,
    tokens_out BIGINT DEFAULT 0,
    cost_usd DOUBLE PRECISION DEFAULT 0,
    duration_ms BIGINT DEFAULT 0,
    model TEXT,
    timestamp DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_obs_events_thread ON observability_events(thread_id);
CREATE INDEX IF NOT EXISTS idx_obs_events_type ON observability_events(event_type);
CREATE INDEX IF NOT EXISTS idx_obs_events_expires ON observability_events(expires_at);

CREATE TABLE IF NOT EXISTS observability_sessions (
    thread_id TEXT PRIMARY KEY,
    user_hash TEXT NOT NULL,
    start_time DOUBLE PRECISION NOT NULL,
    end_time DOUBLE PRECISION,
    duration_seconds DOUBLE PRECISION,
    status TEXT DEFAULT 'running',
    subagent_count INTEGER DEFAULT 0,
    tool_call_count INTEGER DEFAULT 0,
    total_tokens_in BIGINT DEFAULT 0,
    total_tokens_out BIGINT DEFAULT 0,
    total_cost_usd DOUBLE PRECISION DEFAULT 0,
    model_used TEXT,
    expires_at DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_obs_sessions_start ON observability_sessions(start_time DESC);
CREATE INDEX IF NOT EXISTS idx_obs_sessions_status ON observability_sessions(status);

CREATE TABLE IF NOT EXISTS observability_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id TEXT NOT NULL,
    subagent_name TEXT,
    tool_name TEXT,
    error_message TEXT,
    timestamp DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_obs_errors_thread ON observability_errors(thread_id);
CREATE INDEX IF NOT EXISTS idx_obs_errors_timestamp ON observability_errors(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_obs_errors_expires ON observability_errors(expires_at);
"""

_pool = None
_pool_loop: asyncio.AbstractEventLoop | None = None
_pg_broken_until = 0.0
_RETRY_AFTER_S = 60.0


def _conninfo() -> str:
    url = (settings.DATABASE_URL or "").strip()
    if url and "sslmode=" not in url and "supabase" in url:
        sep = "&" if "?" in url else "?"
        url = f"{url}{sep}sslmode=require"
    return url


async def get_pg_pool():
    """Shared AsyncConnectionPool, or None when Postgres is unavailable.

    First successful call also applies the schema (idempotent) and logs the
    durable-tier status loudly so prod diagnosis is one grep.
    """
    global _pool, _pool_loop, _pg_broken_until
    conninfo = _conninfo()
    if not conninfo:
        return None
    if time.monotonic() < _pg_broken_until:
        return None

    try:
        current_loop = asyncio.get_running_loop()
    except RuntimeError:
        current_loop = None

    if _pool is not None:
        if _pool_loop is not None and (_pool_loop.is_closed() or _pool_loop is not current_loop):
            try:
                await _pool.close()
            except Exception:  # noqa: BLE001, S110
                pass
            _pool = None
            _pool_loop = None
        else:
            return _pool

    try:
        from psycopg_pool import AsyncConnectionPool

        candidate = AsyncConnectionPool(
            conninfo,
            min_size=settings.PG_POOL_MIN_SIZE,
            max_size=settings.PG_POOL_MAX_SIZE,
            timeout=30,
            max_idle=300,
            open=False,
            kwargs={"autocommit": True, "prepare_threshold": 0},
        )
        await candidate.open(wait=True)
        async with candidate.connection() as conn:
            # Health probe + schema init in one shot — a DB that can't take
            # DDL is useless to us anyway.
            await conn.execute("SELECT 1")
            await conn.execute(_SCHEMA_SQL)
            await conn.execute(
                "INSERT INTO schema_migrations (version, applied_at) VALUES ($1, $2) "
                "ON CONFLICT (version) DO NOTHING",
                (_SCHEMA_VERSION, time.time()),
            )
        _pool = candidate
        _pool_loop = current_loop
        logger.info("pg durable tier: CONNECTED (pool max=%d)", settings.PG_POOL_MAX_SIZE)
        return _pool
    except Exception as exc:  # noqa: BLE001
        _pg_broken_until = time.monotonic() + _RETRY_AFTER_S
        logger.warning("pg durable tier: DEGRADED (%s) — stores fall back to SQLite/memory", exc)
        try:
            await candidate.close()
        except Exception:  # noqa: BLE001, S110
            pass
        return None


def mark_pg_broken() -> None:
    """Drop the pool after a mid-run failure; next call retries after the window."""
    global _pool, _pool_loop, _pg_broken_until
    _pg_broken_until = time.monotonic() + _RETRY_AFTER_S
    pool, _pool, _pool_loop = _pool, None, None
    if pool is not None:
        try:
            asyncio.get_running_loop().create_task(pool.close())
        except RuntimeError:
            pass


async def pg_fetchone(sql: str, params: tuple = ()) -> dict | None:
    pool = await get_pg_pool()
    if pool is None:
        return None
    try:
        from psycopg.rows import dict_row

        async with pool.connection() as conn:
            cur = await conn.cursor(row_factory=dict_row).execute(sql, params)
            return await cur.fetchone()
    except Exception as exc:  # noqa: BLE001
        logger.warning("pg_fetchone failed: %s", exc)
        mark_pg_broken()
        return None


async def pg_fetch(sql: str, params: tuple = ()) -> list[dict] | None:
    pool = await get_pg_pool()
    if pool is None:
        return None
    try:
        from psycopg.rows import dict_row

        async with pool.connection() as conn:
            cur = await conn.cursor(row_factory=dict_row).execute(sql, params)
            return await cur.fetchall()
    except Exception as exc:  # noqa: BLE001
        logger.warning("pg_fetch failed: %s", exc)
        mark_pg_broken()
        return None


async def pg_execute(sql: str, params: tuple = ()) -> int:
    """Run a write; returns affected rowcount, or -1 when PG is unavailable."""
    pool = await get_pg_pool()
    if pool is None:
        return -1
    try:
        async with pool.connection() as conn:
            cur = await conn.execute(sql, params)
            return cur.rowcount
    except Exception as exc:  # noqa: BLE001
        logger.warning("pg_execute failed: %s", exc)
        mark_pg_broken()
        return -1


async def cleanup_expired_pg() -> int:
    """Delete expired rows — mirrors sqlite_fallback.cleanup_expired."""
    pool = await get_pg_pool()
    if pool is None:
        return 0
    now = time.time()
    total = 0
    try:
        for table in ("shares", "sessions", "research_cache", "files",
                      "observability_events", "observability_errors", "observability_sessions"):
            total += await pg_execute(f"DELETE FROM {table} WHERE expires_at < $1", (now,))
        total += await pg_execute("DELETE FROM rate_limits WHERE timestamp < $1", (now - 3600,))
        if total > 0:
            logger.info("pg cleanup: deleted %d expired rows", total)
    except Exception as exc:  # noqa: BLE001
        logger.warning("pg cleanup failed: %s", exc)
    return max(total, 0)


async def close_pg_pool() -> None:
    global _pool, _pool_loop, _pg_broken_until
    if _pool is not None:
        try:
            await _pool.close()
        except Exception:  # noqa: BLE001, S110
            pass
    _pool = None
    _pool_loop = None
    _pg_broken_until = 0.0


# ---------------------------------------------------------------------------
# SQLite-dialect compatibility adapter
# ---------------------------------------------------------------------------
# The durable stores were written against aiosqlite (``?`` placeholders,
# ``INSERT OR REPLACE``). To make Postgres the primary durable tier without
# rewriting ~50 call sites, ``get_durable_db()`` returns a ``PgCompat``
# connection that accepts the SAME SQL and translates it to PG dialect.
# When Postgres is unavailable it returns the plain aiosqlite connection —
# so the durable tier degrades exactly as before.

_PK: dict[str, str | tuple[str, ...]] = {
    "threads": "thread_id",
    "shares": "token",
    "sessions": "session_id",
    "costs_session": "thread_id",
    "feedback": "key",
    "security_flags": "flag_id",
    "security_cooldowns": "user_hash",
    "research_cache": "key",
    "geocode_cache": "query_hash",
    "files": "file_id",
    "observability_sessions": "thread_id",
    "rate_limits": ("key", "timestamp"),
}

_OR_REPLACE_RE = re.compile(
    r"INSERT\s+OR\s+REPLACE\s+INTO\s+(\w+)\s*\(([^)]*)\)\s*VALUES",
    re.IGNORECASE,
)
_OR_IGNORE_RE = re.compile(
    r"INSERT\s+OR\s+IGNORE\s+INTO\s+(\w+)", re.IGNORECASE,
)


def _translate_sql(sql: str) -> str:
    """Translate the SQLite dialect used by store call sites to Postgres."""
    sql = sql.strip().rstrip(";")

    # INSERT OR REPLACE INTO t (cols) VALUES (…) →
    #   INSERT INTO t (cols) VALUES (…) ON CONFLICT (pk) DO UPDATE SET c=EXCLUDED.c
    m = _OR_REPLACE_RE.search(sql)
    if m:
        table, cols = m.group(1), [c.strip() for c in m.group(2).split(",")]
        sql = f"INSERT INTO {table} ({m.group(2)}) VALUES{sql[m.end():]}"
        pk = _PK.get(table)
        if pk is not None:
            pk_cols = (pk,) if isinstance(pk, str) else pk
            updates = ", ".join(f"{c} = EXCLUDED.{c}" for c in cols if c not in pk_cols)
            clause = f"ON CONFLICT ({', '.join(pk_cols)})"
            clause += f" DO UPDATE SET {updates}" if updates else " DO NOTHING"
            sql = f"{sql} {clause}"

    # INSERT OR IGNORE INTO t … → INSERT INTO t … ON CONFLICT DO NOTHING
    elif _OR_IGNORE_RE.search(sql):
        sql = f"{_OR_IGNORE_RE.sub(chr(92) + '1', sql)} ON CONFLICT DO NOTHING"

    # ? placeholders → %s (none of our SQL embeds a literal '?' in strings)
    return sql.replace("?", "%s")


class _PgRow(dict):
    """dict row that also supports positional access like sqlite3.Row."""

    __slots__ = ("_order",)

    def __init__(self, order: list[str], values: tuple):
        super().__init__(zip(order, values))
        self._order = order

    def __getitem__(self, key):
        if isinstance(key, int):
            return super().__getitem__(self._order[key])
        return super().__getitem__(key)


class _PgCursor:
    """Async cursor facade matching the aiosqlite cursor surface stores use."""

    def __init__(self, rows: list[_PgRow], rowcount: int):
        self._rows = rows
        self.rowcount = rowcount
        self._idx = 0

    async def fetchone(self):
        if self._idx >= len(self._rows):
            return None
        row = self._rows[self._idx]
        self._idx += 1
        return row

    async def fetchall(self):
        rows = self._rows[self._idx:]
        self._idx = len(self._rows)
        return rows


class PgCompat:
    """aiosqlite-shaped connection backed by the shared PG pool.

    ``commit()`` is a no-op (pool connections run autocommit); ``execute()``
    returns a cursor with fetchone/fetchall/rowcount. Errors mark the pool
    broken and re-raise so store call sites fall back exactly like a SQLite
    failure does today.
    """

    async def execute(self, sql: str, params: tuple = ()):
        pool = await get_pg_pool()
        if pool is None:
            raise RuntimeError("pg pool unavailable")
        try:
            from psycopg.rows import tuple_row

            async with pool.connection() as conn:
                cur = await conn.cursor(row_factory=tuple_row).execute(
                    _translate_sql(sql), params,
                )
                desc = cur.description or []
                order = [d.name for d in desc]
                raw = await cur.fetchall() if desc else []
                rows = [_PgRow(order, r) for r in raw]
                return _PgCursor(rows, cur.rowcount)
        except Exception:
            mark_pg_broken()
            raise

    async def commit(self) -> None:  # autocommit pool — present for parity
        return None


async def get_durable_db():
    """Primary durable handle: PgCompat when Postgres is up, else SQLite conn.

    Drop-in replacement for ``get_sqlite_connection()`` — returns None only
    when BOTH Postgres and SQLite are unavailable.
    """
    if await get_pg_pool() is not None:
        return PgCompat()
    from sqlite_fallback import get_sqlite_connection

    return await get_sqlite_connection()
